In [ ]:
# NumPy: матрицы и операции над ними (Версия для Python 3)

In [6]:
import numpy as np

In [7]:
a = np.array([[1, 2, 3], [2, 5, 6], [6, 7, 4]])
print('Matrix:\n', a)

Matrix:
 [[1 2 3]
 [2 5 6]
 [6 7 4]]


In [10]:
b = np.random.randn(5, 5)
b

array([[-1.09520324,  0.16362784, -0.48658037,  0.16380447, -0.10153888],
       [-0.54438382,  0.15837333, -0.14818428, -0.10760995, -0.7076758 ],
       [ 1.21976745,  0.48250384, -0.32119335, -0.12461671,  0.51684212],
       [-0.2595398 ,  0.14025254, -0.97623096, -0.08879162, -1.32353936],
       [ 0.54465651,  1.26892719, -0.65143407,  0.66976993,  0.86218582]])

In [11]:
v = np.arange(0, 24, 2)
print("Вектор-столбец:\n", v)

Вектор-столбец:
 [ 0  2  4  6  8 10 12 14 16 18 20 22]


In [12]:
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])

In [13]:
print("Вектор:\n", a)
print("Его размерность:\n", a.shape)
print("Двумерный массив:\n", b)
print("Его размерность:\n", b.shape)

Вектор:
 [1 2 3]
Его размерность:
 (3,)
Двумерный массив:
 [[1]
 [2]
 [3]]
Его размерность:
 (3, 1)


In [14]:
from scipy import linalg

In [17]:
m1 = np.random.randn(2, 2)
m2 = np.random.randn(2, 2)
print(m1)

[[ 0.80595702 -0.46423292]
 [-0.89989759 -0.00736634]]


In [18]:
print(m2)

[[0.65655325 0.36679532]
 [2.42373328 1.61900326]]


In [19]:
x = linalg.solve(m1, m2)
print(x)

[[-2.64418913 -1.76751091]
 [-6.00486503 -3.85869477]]


In [21]:
o = np.dot(m1, m2)
print(o)

[[-0.59602308 -0.45597335]
 [-0.60868473 -0.34200435]]


In [22]:
f = np.transpose(m1)
print(f)

[[ 0.80595702 -0.89989759]
 [-0.46423292 -0.00736634]]


In [23]:
m1 = np.random.randn(2, 3)

In [24]:
m1

array([[ 2.02584525,  0.54117327, -0.72762674],
       [-0.66662237, -0.48296099,  0.53069003]])

## Транспонирование матриц

In [25]:
f = np.transpose(m1)
f

array([[ 2.02584525, -0.66662237],
       [ 0.54117327, -0.48296099],
       [-0.72762674,  0.53069003]])

In [26]:
m1.T

array([[ 2.02584525, -0.66662237],
       [ 0.54117327, -0.48296099],
       [-0.72762674,  0.53069003]])

## Определение детерминанта

In [27]:
a = np.array([[1, 2, 3], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
det = np.linalg.det(a)
det

1.0

## Ранг матрицы

In [28]:
a = np.array([[1, 2, 3], [1, 1, 1], [2, 2, 2]])
matrix_rank = np.linalg.matrix_rank(a)
matrix_rank

2

## Системы линейных уравнений

In [29]:
a = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(a, b)
x

array([2., 3.])

In [30]:
print(a.dot(x))

[9. 8.]


## Обращение матриц

In [31]:
a = np.array([[1, 2, 1], [1, 1, 4], [2, 3, 6]], dtype=np.float32)
b = np.linalg.inv(a)
b

array([[ 6.,  9., -7.],
       [-2., -4.,  3.],
       [-1., -1.,  1.]], dtype=float32)

## Собственные числа и собственные вектора матрицы

In [32]:
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

In [33]:
print("Матрица A:\n", a)
print("Собственные числа:\n", w)
print("Собственные векторы:\n", v)

Матрица A:
 [[-1 -6]
 [ 2  6]]
Собственные числа:
 [2. 3.]
Собственные векторы:
 [[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


##  Комплексные числа в питоне

In [34]:
a = 3 + 2j
b = 1j

In [35]:
print("Комплексное число a:\n", a)
print("Комплексное число b:\n", b)

Комплексное число a:
 (3+2j)
Комплексное число b:
 1j


In [36]:
c = a * a
d = a / (4 - 5j)

In [37]:
print("Комплексное число c:\n", c)
print("Комплексное число d:\n", d)

Комплексное число c:
 (5+12j)
Комплексное число d:
 (0.0487804878048781+0.5609756097560976j)


# NumPy: векторы и операции над ними (Версия для Python 3)

## В NumPy вектор - это одномерный массив из n-элементов

In [38]:
import numpy as np

In [39]:
a = np.array([1, 2, 3, 4])
print('Вектор:\n', a)

Вектор:
 [1 2 3 4]


In [40]:
b = np.array([1, 2, 3, 4, 5], dtype=float)
print('Вещественный вектор:\n', b)

Вещественный вектор:
 [1. 2. 3. 4. 5.]


In [41]:
c = np.array([True, False, True], dtype=bool)
print('Булевский вектор:\n', c)

Булевский вектор:
 [ True False  True]


In [42]:
d = np.arange(start=10, stop=20, step=2) # последнее значение не включается!
print('Вектор чисел от 10 до 20 с шагом 2:\n', d)

Вектор чисел от 10 до 20 с шагом 2:
 [10 12 14 16 18]


## Операции над векторами

In [43]:
a = np.array([1, 2, 3])
b = np.array([6, 5, 4])
k = 2

print('Вектор a:', a)
print('Вектор b:', b)
print('Число k:', k)

Вектор a: [1 2 3]
Вектор b: [6 5 4]
Число k: 2


In [44]:
print('Сумма a и b:\n', a + b)

Сумма a и b:
 [7 7 7]


In [45]:
print('Разность a и b:\n', a - b)

Разность a и b:
 [-5 -3 -1]


In [46]:
print('Покоординатное умножение a и b:\n', a * b )

Покоординатное умножение a и b:
 [ 6 10 12]


In [47]:
print('Умножение вектора на число (осуществляется покоординатно):\n', k * a)

Умножение вектора на число (осуществляется покоординатно):
 [2 4 6]


## Нормы векторов

In [48]:
from numpy.linalg import norm

In [49]:
a = np.array([1, 2, -3])
print('Вектор a:', a)

Вектор a: [ 1  2 -3]


In [50]:
print('L1 норма вектора a:\n', norm(a, ord=1))

L1 норма вектора a:
 6.0


In [51]:
print('L2 норма вектора a:\n', norm(a, ord=2))

L2 норма вектора a:
 3.7416573867739413


## Расстояния между векторами

In [52]:
a = np.array([1, 2, -3])
b = np.array([-4, 3, 8])
print('Вектор a:', a)
print('Вектор b:', b)

Вектор a: [ 1  2 -3]
Вектор b: [-4  3  8]


In [53]:
print('L1 расстояние между векторами a и b:\n', norm(a - b, ord=1))

L1 расстояние между векторами a и b:
 17.0


In [54]:
print('L2 расстояние между векторами a и b:\n', norm(a - b, ord=2))

L2 расстояние между векторами a и b:
 12.12435565298214


##  Скалярное произведение и угол между векторами

In [55]:
a = np.array([0, 5, -1])
b = np.array([-4, 9, 3])
print('Вектор a:', a)
print('Вектор b:', b)

Вектор a: [ 0  5 -1]
Вектор b: [-4  9  3]


In [56]:
print('Скалярное произведение a и b (через функцию):', np.dot(a, b))

Скалярное произведение a и b (через функцию): 42


In [57]:
print('Скалярное произведение a и b (через метод):', a.dot(b))

Скалярное произведение a и b (через метод): 42


In [58]:
cos_angle = np.dot(a, b) / norm(a) / norm(b)
print('Косинус угла между a и b:', cos_angle)
print('Сам угол:', np.arccos(cos_angle))

Косинус угла между a и b: 0.8000362836474323
Сам угол: 0.6434406336093618


# Задача 1: сравнение предложений

## Дан набор предложений, скопированных с Википедии. Каждое из них имеет "кошачью тему" в одном из трех смыслов:

* кошки (животные)
* UNIX-утилита cat для вывода содержимого файлов
* версии операционной системы OS X, названные в честь семейства кошачьих
Ваша задача — найти два предложения, которые ближе всего по смыслу к расположенному в самой первой строке. В качестве меры близости по смыслу мы будем использовать косинусное расстояние.

In [4]:
import numpy as np

In [6]:
import scipy

In [47]:
from numpy import zeros, dot, savetxt
from numpy.linalg import norm
 
# Definition of a cosine distance function
# according to scipy.spatial.distance.cosine function's description 
def cosine_distance(u, v):
    return 1.0 - (dot(u, v) / (norm(u) * norm(v)))
 
if __name__ == "__main__":
    with open("sentences.txt") as f:
        # Let's determine a number of lines in a text file
        lines = sum(1 for _ in f)
        f.seek(0)
        
        import re
        words = {}
        # The 'lcount' variable controlls the index of a current line in the text file,
        # when the 'wcount' variable controlls the index of a unique word.
        lcount, wcount = 0, 0
        for line in f:
            # Here we compile a pattern object, read a line from the text file,
            # and split it into tokens (words).
            p = re.compile(r"[^a-z]+")
            tokens = p.split(line.lower())
            # In this case we will have only one empty token at the end of a list.
            # Let's remove it.
            tokens.pop()
            for token in tokens:
                # If a token is not presented in the dictionary yet then we add it.
                # The value of the 'occurrences' entry is a list object where every item represents
                # a specific line in the text file. The first item represents the first line, the second item
                # represents the sencond line etc. 
                if token not in words:
                    words[token] = {
                        "index": wcount,
                        "occurrences": [0] * lines
                    }
                    wcount += 1
                # If we find the same token in the same list of tokens (in the same line)
                # then we just ignore it.
                elif words[token]["occurrences"][lcount] != 0:
                    continue
                
                # Here we register how many times a token occured in a list of tokens (in a line)    
                words[token]["occurrences"][lcount] = tokens.count(token)    
            lcount += 1
        
        # Here we create a numpy-array, filled with zeros
        arr = zeros((lines, len(words)))
        
        # Now for every word in the dictionary we take a number of its occurrences
        # in every line and put it to the array.  
        for word in words:
            i, j = 0, words[word]["index"]
            for occ in words[word]["occurrences"]:
                arr[i, j] = occ
                i += 1
    
        #savetxt("foo.csv", arr, delimiter=",")
        
        # Finally we calculate a cosine distance between the first sentence (line) and
        # other sentences in the text file
        dist = [] 
        u = arr[0,] 
        for i in range(1, lines):
            v = arr[i,]
            dist.append({"index": i, "distance": cosine_distance(u, v)})    
        
        dist.sort(key=lambda x: x["distance"])
        print("The 1st closest sentence is a sentence #%d with a cosine distance of %.2f.\n"\
        "The 2nd closest sentence is a sentence #%d with a cosine distance of %.2f." % (
            dist[0]["index"],
            dist[0]["distance"],
            dist[1]["index"],
            dist[1]["distance"]
        ))

The 1st closest sentence is a sentence #6 with a cosine distance of 0.73.
The 2nd closest sentence is a sentence #4 with a cosine distance of 0.78.
